### PR TITLE
✨ Add /work and /crime commands with cooldown logic

### PR DESCRIPTION
**Pull request by JustYourBud**
## Additions
- ✨ Create Job class with jobs, descriptions, and other info
- ✨ Add updateBalance() to update a user's balance
- ✨ #6 
- ✨ Add the cooldown logic
- ✨ Create Crime class with crimes, descriptions, and other info
- ✨ #7 

- [x] The additons and changes made have been tested.

### CODE REVIEW

**Comment by jonahbedouch** [comment]
Generally looks good, I have two notes: 
 * Having crime be a subclass of work feels weird, since then you're doing the work of choosing a job description twice, once for work and then overriding it with crime. Maybe create a generic "Job" class with just the payout and message getter logic, then extend for both work and crime with the actual assignment of messages?
 * You use `[]` to represent an array in interfaces which is fine, but to me I always have found the `Array<>` notation more intuitive. This is an optional change but I'd recommend it since it's easy to miss the braces.

Both of these are kind of opinionated though and your code is fine to push if you disagree, LGTM

**Review by jonahbedouch — APPROVED** [review]
Generally looks good, I have two notes:
 * Having crime be a subclass of work feels weird, since then you're doing the work of choosing a job description twice, once for work and then overriding it with crime. Maybe create a generic "Job" class with just the payout and message getter logic, then extend for both work and crime with the actual assignment of messages?
 * You use `[]` to represent an array in interfaces which is fine, but to me I always have found the `Array<>` notation more intuitive. This is an optional change but I'd recommend it since it's easy to miss the braces.

Both of these are opinionated, though, and there's no right way to go about it. Up to you.

Also, I have a feature request related to this: Instead of relying on a formatted time for your cooldown text in markdown, I would strongly recommend using Discord's dynamic timestamp feature, which you can read more about [in this reddit thread](https://www.reddit.com/r/discordapp/comments/ofsm4e/dynamic_timestamps/).

Since everything here is in working order, I'm going to go ahead and approve you to merge, but I'd recommend making those changes either in this PR or in another one. If you make them here, ping me and I'd be happy to re-review.

**Comment by JustYourBud** [comment]
@jonahbedouch 
> Having crime be a subclass of work feels weird, since then you're doing the work of choosing a job description twice, once for work and then overriding it with crime. Maybe create a generic "Job" class with just the payout and message getter logic, then extend for both work and crime with the actual assignment of messages?

Ended up doing something similar to this as per our co-authored https://github.com/BudWorks/Akaei/pull/68/commits/c2fee68011b39ee2ea3a444b71bf3ec69ecec6de commit.

> You use [] to represent an array in interfaces which is fine, but to me I always have found the Array<> notation more intuitive. This is an optional change but I'd recommend it since it's easy to miss the braces.

Did this as well in https://github.com/BudWorks/Akaei/pull/68/commits/8db0316bf76dac658204c9dd7709e5dbf2c873d4.

Only thing I didn't do was the Discord timestamp suggestion, only because I'm picky about how the time displays and I just don't like how Discord handles them for this specific scenario. I'm sure I'll find a use for them though.

Everything's been tested and works so if you wanna re-review it for anything else that would be great 👍

## Changes
- 💎 Use `Array<>` notation in User interface
- 📦 Refactor the Job class and related classes

**Review by jonahbedouch — CHANGES_REQUESTED** [review]
I see a problem with implementation of Job class that doesn't impact code here, but is more of a conceptual misalignment of the class's purpose with the real world. Each Job instance is meant to represent a single job someone has offered you, so making the job pay random on every call to "pay" (as opposed to giving the job a single pay value in the constructor within the range feels as though it'd be problematic going forward if modifications are made to work/crime. I would have it set a pay value in the constructor and just return it on call to pay, as to ensure that the job class accurately reflects job offers in the real world.

**Comment by JustYourBud** [comment]
Yeah that was a bug, it's all fixed up now and works as intended.

## Fixes
- 🐛 Fix payment being inconsistent on each call

**Review by jonahbedouch — APPROVED** [review]
Alright, everything looks good to me then, you're good to merge!

**Pull request merged**
